"""Golden test: TwoStageCtle.process() against MATLAB COM3.70's own
TD_CTLE (com_ieee8023_93a_370.m:2228-2243), a bilinear-transform IIR
filter -- the time-domain path MATLAB's real pipeline uses (unlike this
project's own frequency-domain transfer_function()), called twice in
sequence for the CL120d two-stage structure
(com_ieee8023_93a_370.m:5925,5930), applied to a unit impulse (TD_CTLE
is LTI, so its output on an impulse is its own impulse response).

TDD: written against process()'s current stub (raises
NotImplementedError) -- should fail until implemented. Ground truth
generated by matlab_golden/generate/gen_td_ctle.m, using this project's
own real C2C config CTLE point (already verified in the frequency
domain, tests/ctle/test_two_stage_vs_matlab.py).
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

from serdeskit.common.types import Signal
from serdeskit.ctle import TwoStageCtle

DATA = Path(__file__).parent.parent.parent / "matlab_golden" / "data" / "td_ctle_impulse_response.csv"

BAUD_RATE = 53.125e9
SAMPLES_PER_UI = 32


def test_process_matches_matlab() -> None:
    with open(DATA) as f:
        rows = list(csv.DictReader(f))
    expected = np.array([float(r["response"]) for r in rows])

    impulse = np.zeros(len(expected))
    impulse[0] = 1.0
    sig = Signal(samples=impulse, fs=BAUD_RATE * SAMPLES_PER_UI, t0=0.0)

    ctle = TwoStageCtle(
        zero_freq=21.25e9,
        pole1_freq=21.25e9,
        pole2_freq=53.125e9,
        shelf_freq=0.6640625e9,
        dc_gain_db=-3.0,
        shelf_gain_db=-2.0,
    )
    actual = ctle.process(sig).samples

    np.testing.assert_allclose(actual, expected, rtol=1e-6, atol=1e-12)
