"""Golden test: TwoStageCtle.transfer_function() against MATLAB
COM3.70's own CL120d two-stage CTLE formula (the inline `ctle_gain` /
`H_low` computation in optimize_fom -- our configs' own CTLE_type,
confirmed by param.CTLE_type's own resolution logic: 'CL93' unless
g_DC_HP_values is present in the config, which every config this project
has exercised has).

Ground truth generated by matlab_golden/generate/gen_ctle.m, using the
C2C config's own CTLE frequencies and MATLAB's own found-optimal gains
for it. See matlab_golden/README.md.
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

from serdeskit.ctle import TwoStageCtle

DATA = Path(__file__).parent.parent.parent / "matlab_golden" / "data" / "ctle_two_stage.csv"


def test_two_stage_matches_matlab() -> None:
    with open(DATA) as f:
        rows = list(csv.DictReader(f))
    freqs = np.array([float(r["freq"]) for r in rows])
    expected = np.array([complex(float(r["h_r"]), float(r["h_i"])) for r in rows])

    ctle = TwoStageCtle(
        zero_freq=21.25e9,
        pole1_freq=21.25e9,
        pole2_freq=53.125e9,
        shelf_freq=0.6640625e9,
        dc_gain_db=-3.0,
        shelf_gain_db=-2.0,
    )
    actual = ctle.transfer_function(freqs)

    np.testing.assert_allclose(actual, expected, rtol=1e-9, atol=1e-12)
