"""Golden test: TapWeightFfe.process() against MATLAB COM3.70's own FFE
(matlab_golden/lib/FFE.m) applied directly to a delta impulse -- the
time-domain circshift-based tap-delay sum MATLAB's real pipeline uses
(unlike this project's own transfer_function(), which
tests/ffe/test_tap_weight_vs_matlab.py already checks via FFE's FFT).

TDD: written against process()'s current stub (raises
NotImplementedError) -- should fail until implemented. Ground truth
generated by matlab_golden/generate/gen_ffe.m, the same FFE(C, cmx, spui,
delta) call test_tap_weight_vs_matlab.py's own ground truth comes from,
just keeping the time-domain output (V0) instead of only its FFT.
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

from serdeskit.common.types import Signal
from serdeskit.ffe import TapWeightFfe

DATA = Path(__file__).parent.parent.parent / "matlab_golden" / "data" / "ffe_time_domain.csv"

TAP_WEIGHTS = np.array([0.1, -0.05])  # [pre1, post1] -- cursor (0.85) is derived
N_POST = 1
SAMPLES_PER_UI = 8  # gen_ffe.m's own spui
TAP_DELAY = 1.25e-11  # matches test_tap_weight_vs_matlab.py's own value
FS = SAMPLES_PER_UI / TAP_DELAY


def test_process_matches_matlab() -> None:
    with open(DATA) as f:
        rows = list(csv.DictReader(f))
    expected = np.array([float(r["response"]) for r in rows])

    delta = np.zeros(len(expected))
    delta[0] = 1.0
    sig = Signal(samples=delta, fs=FS, t0=0.0)

    ffe = TapWeightFfe(tap_weights=TAP_WEIGHTS, n_post=N_POST, tap_delay=TAP_DELAY)
    actual = ffe.process(sig).samples

    np.testing.assert_allclose(actual, expected, rtol=1e-9, atol=1e-12)
