"""Golden test: TapWeightFfe.transfer_function() against MATLAB
COM3.70's own FFE (a time-domain circshift-based tap-delay sum), via its
FFT on a delta impulse.

Ground truth generated by matlab_golden/generate/gen_ffe.m, calling
matlab_golden/lib/FFE.m directly. See matlab_golden/README.md.

MATLAB's `FFE` references zero delay at the *cursor* tap (precursor taps
get a negative circshift, postcursor taps positive) -- this test asserts
TapWeightFfe.transfer_function() uses that same convention directly, with
no compensating delay factor.
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

from serdeskit.ffe import TapWeightFfe

DATA = Path(__file__).parent.parent.parent / "matlab_golden" / "data" / "ffe_fft.csv"

TAP_WEIGHTS = np.array([0.1, -0.05])  # [pre1, post1] -- cursor (0.85) is derived
N_POST = 1
TAP_DELAY = 1.25e-11  # 1 UI, arbitrary for this test (only the ratio to sample rate matters)


def test_transfer_function_matches_matlab() -> None:
    with open(DATA) as f:
        rows = list(csv.DictReader(f))
    cycles_per_sample = np.array([float(r["cycles_per_sample"]) for r in rows])
    samples_per_ui = float(rows[0]["samples_per_ui"])
    expected = np.array([complex(float(r["h_r"]), float(r["h_i"])) for r in rows])

    # cycles/sample -> Hz: sample_rate = samples_per_ui / tap_delay.
    freqs = cycles_per_sample * samples_per_ui / TAP_DELAY

    ffe = TapWeightFfe(tap_weights=TAP_WEIGHTS, n_post=N_POST, tap_delay=TAP_DELAY)
    actual = ffe.transfer_function(freqs)

    np.testing.assert_allclose(actual, expected, rtol=1e-9, atol=1e-12)
