"""Golden test: TapWeightFfe.transfer_function() against MATLAB
COM3.70's own FFE (a time-domain circshift-based tap-delay sum), via its
FFT on a delta impulse.

Ground truth generated by matlab_golden/generate/gen_ffe.m, calling
matlab_golden/lib/FFE.m directly. See matlab_golden/README.md.

Delay-convention note: MATLAB's `FFE` references zero delay at the
*cursor* tap (precursor taps get a negative circshift, postcursor taps
positive). TapWeightFfe.transfer_function() references zero delay at the
*first* (most-precursor) tap instead (93A-21's own convention, delays
0, 1, 2, ...). These aren't the same H(f) -- they differ by a pure
linear phase, exp(+j*2*pi*f*n_pre*tap_delay), exactly the delay between
"first tap" and "cursor tap" (n_pre tap positions). Not a bug: this
project tracks absolute timing separately via Signal.t0 rather than
folding it into any one stage's own transfer function, so a per-stage
delay reference is free to differ as long as it's consistent -- this
test verifies the *shape* matches MATLAB exactly once that expected,
derived delay factor is accounted for.
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

from serdeskit.ffe import TapWeightFfe

DATA = Path(__file__).parent.parent.parent / "matlab_golden" / "data" / "ffe_fft.csv"

TAP_WEIGHTS = np.array([0.1, -0.05])  # [pre1, post1] -- cursor (0.85) is derived
N_POST = 1
N_PRE = len(TAP_WEIGHTS) - N_POST
TAP_DELAY = 1.25e-11  # 1 UI, arbitrary for this test (only the ratio to sample rate matters)


def test_transfer_function_matches_matlab_up_to_known_delay_convention() -> None:
    with open(DATA) as f:
        rows = list(csv.DictReader(f))
    cycles_per_sample = np.array([float(r["cycles_per_sample"]) for r in rows])
    samples_per_ui = float(rows[0]["samples_per_ui"])
    expected = np.array([complex(float(r["h_r"]), float(r["h_i"])) for r in rows])

    # cycles/sample -> Hz: sample_rate = samples_per_ui / tap_delay.
    freqs = cycles_per_sample * samples_per_ui / TAP_DELAY

    ffe = TapWeightFfe(tap_weights=TAP_WEIGHTS, n_post=N_POST, tap_delay=TAP_DELAY)
    actual = ffe.transfer_function(freqs)

    delay_factor = np.exp(1j * 2 * np.pi * freqs * N_PRE * TAP_DELAY)
    np.testing.assert_allclose(actual * delay_factor, expected, rtol=1e-9, atol=1e-12)
