"""Golden test: TapWeightRxFfe.process() against MATLAB COM3.70's own
force() (matlab_golden/lib/force.m, copied verbatim) -- the function
that actually applies Rx FFE to the signal path (com_ieee8023_93a_370.m:
732, inside Apply_EQ, called with fom_result's own already-chosen RxFFE
coefficients). This is the version that feeds Apply_EQ's
chdata(i).eq_pulse_response, which get_pdf() (the real COM/ISI/noise
calculation) actually reads -- not fom_result.sbr, which never applies
Rx FFE at all (see docs/known-issues.md's "full composed pulse response"
entry for how that distinction was found).

TDD: written against process()'s current stub (raises
NotImplementedError) -- should fail until implemented. Ground truth
generated by matlab_golden/generate/gen_force.m, using cpx=0 (no
post-cursor taps) so force()'s own adaptive "DNH" backoff search
provably can't modify the given taps (confirmed directly: that script's
own console output reports Cmod unchanged from the input C) -- this
keeps the fixture scoped to "does the FFE application match", the same
scope test_tap_weight_process_vs_matlab.py already covers for Tx FFE,
not force()'s separate tap-selection search (out of scope, see that
script's own comment).
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

from serdeskit.common.types import Signal
from serdeskit.rx_ffe import TapWeightRxFfe

DATA = Path(__file__).parent.parent.parent / "matlab_golden" / "data" / "force_rx_ffe.csv"

SAMPLES_PER_UI = 8
TAP_WEIGHTS = np.array([0.05, 0.15, 1.0])  # [pre2, pre1, cursor]
N_PRE = 2
TAP_DELAY = 1.25e-11  # matches this project's other FFE golden tests' own value; only the ratio to fs matters
FS = SAMPLES_PER_UI / TAP_DELAY

PEAK_IDX = 32  # 0-indexed (gen_force.m's peak_idx=33, 1-indexed)


def test_process_matches_matlab() -> None:
    with open(DATA) as f:
        rows = list(csv.DictReader(f))
    expected = np.array([float(r["response"]) for r in rows])

    n = len(expected)
    v = np.array([np.exp(-abs(k - PEAK_IDX) / 10) for k in range(n)])
    sig = Signal(samples=v, fs=FS, t0=0.0)

    rx_ffe = TapWeightRxFfe(tap_weights=TAP_WEIGHTS, tap_delay=TAP_DELAY, n_pre=N_PRE)
    actual = rx_ffe.process(sig).samples

    np.testing.assert_allclose(actual, expected, rtol=1e-9, atol=1e-12)
