"""Golden test: package_transmission_line against MATLAB COM3.70's own
synth_tline, using the C2C config's own package trace parameters.

Ground truth generated by matlab_golden/generate/gen_synth_tline.m,
calling matlab_golden/lib/synth_tline.m directly. See
matlab_golden/README.md.
"""
from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

import numpy as np

from serdeskit.package.transmission_line import package_transmission_line

DATA = Path(__file__).parent.parent.parent / "matlab_golden" / "data" / "synth_tline.csv"

R0 = 50.0
A1 = 0.0009909
A2 = 0.0002772
TAU = 0.006141
GAMMA0 = 0.0


def test_package_transmission_line_matches_matlab() -> None:
    by_segment: dict[tuple[float, float], list[dict[str, str]]] = defaultdict(list)
    with open(DATA) as f:
        for row in csv.DictReader(f):
            by_segment[(float(row["zc"]), float(row["len"]))].append(row)

    for (zc, length), rows in by_segment.items():
        freqs = np.array([float(r["freq"]) for r in rows])
        expected_s11 = np.array([complex(float(r["s11_r"]), float(r["s11_i"])) for r in rows])
        expected_s21 = np.array([complex(float(r["s21_r"]), float(r["s21_i"])) for r in rows])

        network = package_transmission_line(freqs, R0, A1, A2, TAU, GAMMA0, [(zc, length)])

        np.testing.assert_allclose(
            network.s[:, 0, 0], expected_s11, rtol=1e-6, atol=1e-9,
            err_msg=f"S11 mismatch for zc={zc}, len={length}",
        )
        np.testing.assert_allclose(
            network.s[:, 1, 0], expected_s21, rtol=1e-6, atol=1e-9,
            err_msg=f"S21 mismatch for zc={zc}, len={length}",
        )
