"""Golden test: skrf's own `**` two-port cascade operator (what every
piece of serdeskit.package cascades with) against MATLAB COM3.70's own
combines4p, on arbitrary non-reciprocal S-parameter pairs.

Ground truth generated by matlab_golden/generate/gen_combines4p.m,
calling matlab_golden/lib/combines4p.m (an unmodified copy of
com_ieee8023_93a_370.m's own function) directly -- not read-and-guessed,
actually executed. See matlab_golden/README.md.
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np
import skrf

DATA = Path(__file__).parent.parent.parent / "matlab_golden" / "data" / "combines4p.csv"


def _network(s11: np.ndarray, s12: np.ndarray, s21: np.ndarray, s22: np.ndarray, freqs: np.ndarray) -> skrf.Network:
    s = np.zeros((len(freqs), 2, 2), dtype=np.complex128)
    s[:, 0, 0] = s11
    s[:, 0, 1] = s12
    s[:, 1, 0] = s21
    s[:, 1, 1] = s22
    return skrf.Network(s=s, f=freqs, z0=50.0, f_unit="Hz")


def test_skrf_cascade_matches_matlab_combines4p() -> None:
    with open(DATA) as f:
        rows = list(csv.DictReader(f))
    freqs = np.array([float(r["idx"]) + 1.0 for r in rows])  # arbitrary distinct frequencies, one per row

    def col(name: str) -> np.ndarray:
        return np.array([complex(float(r[f"{name}_r"]), float(r[f"{name}_i"])) for r in rows])

    net1 = _network(col("s11in1"), col("s12in1"), col("s21in1"), col("s22in1"), freqs)
    net2 = _network(col("s11in2"), col("s12in2"), col("s21in2"), col("s22in2"), freqs)

    cascaded = net1 ** net2

    expected_s11, expected_s12 = col("s11out"), col("s12out")
    expected_s21, expected_s22 = col("s21out"), col("s22out")

    np.testing.assert_allclose(cascaded.s[:, 0, 0], expected_s11, rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(cascaded.s[:, 0, 1], expected_s12, rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(cascaded.s[:, 1, 0], expected_s21, rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(cascaded.s[:, 1, 1], expected_s22, rtol=1e-6, atol=1e-9)
