"""Golden test: cascade_channel + SParameterChannel against MATLAB
COM3.70's own channel+package computation, for a real IEEE 802.3ck "C2C"
channel.

Ground truth generated by matlab_golden/generate/gen_channel_plus_package.m,
replicating s21_pkg_tester's own cascade formula (TX package -> channel
-> RX package, the RX package port-reversed exactly as s21_pkg_tester
itself does) using the already-validated lib/read_Nport_touchstone.m +
lib/make_pkg.m + lib/combines4p.m -- no live end-to-end run needed. See
matlab_golden/README.md.

Package case 1 (13mm TX, 11mm RX -- the config's own per-side lengths,
not the uniform-13mm approximation an earlier version of this test used).

Needs the real channel file (gitignored -- see
examples/compute_com_c2c.py's own docstring for the download link;
CI's own workflow downloads it, see .github/workflows/ci.yml).
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np
import skrf

from serdeskit.channel import differential_network
from serdeskit.package import Package, cascade_channel

THRU_PATH = (
    Path(__file__).parent.parent.parent / "reference" / "ck_channels" / "c2c_pcb" / "C2C_PCB_SYSVIA_12dB_thru.s4p"
)
DATA = Path(__file__).parent.parent.parent / "matlab_golden" / "data" / "channel_plus_package_c2c_thru.csv"

R0 = 50.0
TX_PACKAGE = Package(
    r0=R0,
    die_capacitances=[1.2e-4 * 1e-9],
    die_inductances=[0.12e-9],
    bump_capacitance=0.3e-4 * 1e-9,
    tline_a1=0.0009909,
    tline_a2=0.0002772,
    tline_tau=0.006141,
    tline_gamma0=0.0,
    tline_segments=[(87.5, 13.0), (92.5, 1.8)],
    pad_capacitance=0.87e-4 * 1e-9,
    is_rx=False,
)
RX_PACKAGE = Package(
    r0=R0,
    die_capacitances=[1.2e-4 * 1e-9],
    die_inductances=[0.12e-9],
    bump_capacitance=0.3e-4 * 1e-9,
    tline_a1=0.0009909,
    tline_a2=0.0002772,
    tline_tau=0.006141,
    tline_gamma0=0.0,
    tline_segments=[(87.5, 11.0), (92.5, 1.8)],
    pad_capacitance=0.87e-4 * 1e-9,
    is_rx=True,
)


def test_channel_plus_package_matches_matlab() -> None:
    with open(DATA) as f:
        rows = list(csv.DictReader(f))
    freqs = np.array([float(r["freq"]) for r in rows])
    expected_s11 = np.array([complex(float(r["s11_r"]), float(r["s11_i"])) for r in rows])
    expected_s21 = np.array([complex(float(r["s21_r"]), float(r["s21_i"])) for r in rows])

    network = skrf.Network(str(THRU_PATH))
    diff = differential_network(network, port_order=(0, 2, 1, 3))
    # cascade_channel's own raw output, not SParameterChannel.transfer_function():
    # that method applies a raised-cosine taper across the whole band (for
    # extrapolation safety beyond the measured range, per its own docstring) --
    # a separate, later serdeskit-specific step MATLAB's combines4p-based
    # cascade never applies, so comparing against it here would conflate two
    # different things.
    cascaded = cascade_channel(diff, TX_PACKAGE, RX_PACKAGE, freqs)

    np.testing.assert_allclose(cascaded.s[:, 1, 0], expected_s21, rtol=1e-3, atol=1e-4)
    np.testing.assert_allclose(cascaded.s[:, 0, 0], expected_s11, rtol=1e-3, atol=1e-4)
