"""Golden test: die_model ** package_transmission_line (one block: die
ladder + bump cap, then one tline segment, no board-side cap) against
MATLAB COM3.70's own make_pkg, using the C2C TX package's real "block 1"
parameters.

Ground truth generated by matlab_golden/generate/gen_make_pkg.m, calling
matlab_golden/lib/make_pkg.m directly. See matlab_golden/README.md.
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

from serdeskit.package.die import die_model
from serdeskit.package.transmission_line import package_transmission_line

DATA = Path(__file__).parent.parent.parent / "matlab_golden" / "data" / "make_pkg.csv"

R0 = 50.0


def test_die_plus_tline_matches_matlab_make_pkg() -> None:
    with open(DATA) as f:
        rows = list(csv.DictReader(f))
    freqs = np.array([float(r["freq"]) for r in rows])
    expected_s11 = np.array([complex(float(r["s11_r"]), float(r["s11_i"])) for r in rows])
    expected_s21 = np.array([complex(float(r["s21_r"]), float(r["s21_i"])) for r in rows])

    die = die_model(freqs, R0, capacitances=[1.2e-13], inductances=[1.2e-10], bump_capacitance=3e-14)
    tline = package_transmission_line(
        freqs, R0, a1=0.0009909, a2=0.0002772, tau=0.006141, gamma0=0.0, segments=[(87.5, 13.0)]
    )
    network = die ** tline

    np.testing.assert_allclose(network.s[:, 0, 0], expected_s11, rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(network.s[:, 1, 0], expected_s21, rtol=1e-6, atol=1e-9)
