"""Golden test: Package.network() against MATLAB COM3.70's own
make_full_pkg, for the C2C config's real (4-block, 2 real + 2 no-op)
package parameters.

Ground truth generated by matlab_golden/generate/gen_make_full_pkg.m,
which replicates make_full_pkg's own block loop by calling the real
lib/make_pkg.m + lib/combines4p.m directly -- cross-checked against
make_full_pkg itself, called with a live run's own captured `param`
struct (see matlab_golden/README.md for why that cross-check mattered:
an earlier, less careful capture wasn't tagged by which of the tool's
two package test cases was active, and produced numbers that looked
like a real package-model bug but weren't).

RX orientation note: MATLAB's make_full_pkg builds the RX package the
same "die first" direction as TX (port 1 = die side, port 2 = board
side) -- but serdeskit's Package.network() builds the RX side "board
first" (port 1 = board/channel-facing side), since that's the order
cascade_channel needs (tx.network() ** channel ** rx.network(), where
rx's port 1 must face the incoming channel). For a reciprocal 2-port,
S21 is orientation-independent (S12=S21 either way), but S11 and S22
swap under a port flip -- so the RX comparison here checks S21 directly
against MATLAB's, and S11 against MATLAB's S22 (not S11).
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

from serdeskit.package import Package

R0 = 50.0
TX_PACKAGE = Package(
    r0=R0,
    die_capacitances=[1.2e-4 * 1e-9],
    die_inductances=[0.12e-9],
    bump_capacitance=0.3e-4 * 1e-9,
    tline_a1=0.0009909,
    tline_a2=0.0002772,
    tline_tau=0.006141,
    tline_gamma0=0.0,
    tline_segments=[(87.5, 13.0), (92.5, 1.8)],
    pad_capacitance=0.87e-4 * 1e-9,
    is_rx=False,
)
RX_PACKAGE = Package(
    r0=R0,
    die_capacitances=[1.2e-4 * 1e-9],
    die_inductances=[0.12e-9],
    bump_capacitance=0.3e-4 * 1e-9,
    tline_a1=0.0009909,
    tline_a2=0.0002772,
    tline_tau=0.006141,
    tline_gamma0=0.0,
    tline_segments=[(87.5, 11.0), (92.5, 1.8)],
    pad_capacitance=0.87e-4 * 1e-9,
    is_rx=True,
)

DATA_DIR = Path(__file__).parent.parent.parent / "matlab_golden" / "data"


def _load(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    with open(path) as f:
        rows = list(csv.DictReader(f))
    freqs = np.array([float(r["freq"]) for r in rows])
    s11 = np.array([complex(float(r["s11_r"]), float(r["s11_i"])) for r in rows])
    s21 = np.array([complex(float(r["s21_r"]), float(r["s21_i"])) for r in rows])
    return freqs, s11, s21


def test_tx_package_matches_matlab() -> None:
    freqs, expected_s11, expected_s21 = _load(DATA_DIR / "make_full_pkg_tx.csv")

    network = TX_PACKAGE.network(freqs)

    np.testing.assert_allclose(network.s[:, 0, 0], expected_s11, rtol=1e-6, atol=1e-9)
    np.testing.assert_allclose(network.s[:, 1, 0], expected_s21, rtol=1e-6, atol=1e-9)


def test_rx_package_matches_matlab_port_flipped() -> None:
    freqs, matlab_s11_die_side, expected_s21 = _load(DATA_DIR / "make_full_pkg_rx.csv")

    network = RX_PACKAGE.network(freqs)

    # S21 is orientation-independent for a reciprocal network.
    np.testing.assert_allclose(network.s[:, 1, 0], expected_s21, rtol=1e-6, atol=1e-9)
    # serdeskit's port 1 = board side, MATLAB's port 1 = die side -- flip
    # serdeskit's network back to die-side-first before comparing S11,
    # rather than needing MATLAB's own (unrecorded) S22.
    flipped = network.flipped()
    np.testing.assert_allclose(flipped.s[:, 0, 0], matlab_s11_die_side, rtol=1e-6, atol=1e-9)
