"""Golden test: TxRisetimeFilter.transfer_function() against MATLAB
COM3.70's own H_t (transmitter transition-time filter), the formula
`s21_pkg_tester` bakes into every `chdata(i).sdd21` whenever
`OP.FORCE_TR` is set (com_ieee8023_93a_370.m:9839-9856) -- confirmed
empirically against a real live run to 5.3e-10 precision, see
docs/known-issues.md's "full composed pulse response" entry.

TDD: written against `TxRisetimeFilter`'s current stub (raises
`NotImplementedError`) -- should fail until the real formula is
implemented there. Ground truth generated by
matlab_golden/generate/gen_tx_h_t.m (OP.T_r_filter_type=1,
OP.T_r_meas_point=0 -- the branch OP.FORCE_TR forces every config this
project has exercised into).
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

from serdeskit.tx_filter import TxRisetimeFilter

DATA = Path(__file__).parent.parent.parent / "matlab_golden" / "data" / "tx_h_t.csv"

RISETIME = 0.0075e-9  # seconds -- gen_tx_h_t.m's own OP.transmitter_transition_time (0.0075 ns)


def test_transfer_function_matches_matlab() -> None:
    with open(DATA) as f:
        rows = list(csv.DictReader(f))
    freqs = np.array([float(r["freq"]) for r in rows])
    expected = np.array([complex(float(r["h_r"]), float(r["h_i"])) for r in rows])

    filt = TxRisetimeFilter(risetime=RISETIME)
    actual = filt.transfer_function(freqs)

    np.testing.assert_allclose(actual, expected, rtol=1e-6, atol=1e-9)
