"""Golden test: RxAfeButterworth.transfer_function() against MATLAB
COM3.70's own Butterworth_Filter.

Ground truth generated by matlab_golden/generate/gen_butterworth.m,
calling matlab_golden/lib/Butterworth_Filter.m directly. See
matlab_golden/README.md.
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

from serdeskit.rx_afe import RxAfeButterworth

DATA = Path(__file__).parent.parent.parent / "matlab_golden" / "data" / "butterworth.csv"


def test_transfer_function_matches_matlab() -> None:
    with open(DATA) as f:
        rows = list(csv.DictReader(f))
    freqs = np.array([float(r["freq"]) for r in rows])
    expected = np.array([complex(float(r["h_r"]), float(r["h_i"])) for r in rows])

    afe = RxAfeButterworth(cutoff_freq=0.75 * 53.125e9)
    actual = afe.transfer_function(freqs)

    np.testing.assert_allclose(actual, expected, rtol=1e-6, atol=1e-9)
