"""Golden test: Link.sbr_pulse_response() against MATLAB's real
chdata(i).eq_pulse_response -- what Apply_EQ actually builds
(com_ieee8023_93a_370.m:426, "returns pulse response with CTLE, TXLE,
RXFFE") and get_pdf() (the real COM/ISI/noise calculation) reads. Not
fom_result.sbr, which never applies Rx FFE at all -- see
docs/known-issues.md's "full composed pulse response" entry for how that
distinction was found; this project's own C2C config's Rx FFE happens to
be a single unity tap, which is exactly why sbr_pulse_response()'s other
existing golden test (test_sbr_pulse_response_vs_matlab_c2c.py) didn't
already catch this -- the two quantities coincide there.

TDD: written against sbr_pulse_response()'s current recipe, which has no
Rx FFE step at all -- should fail until rx_ffe.process() is wired in.

Calls Link.sbr_pulse_response() directly (not just its constituent
pieces), via a synthetic Channel whose transfer_function() is chosen so
that grid.truncated_impulse_response() -- Link's own real truncation
step -- reproduces an exact, known array. tx_filter/rx_afe are identity,
so channel.transfer_function() alone determines the composed h.

Ground truth generated by matlab_golden/generate/gen_apply_eq.m, calling
MATLAB's own Apply_EQ (matlab_golden/lib/Apply_EQ.m, copied verbatim) on
that same known array (n=1214, chosen there specifically to match what
SystemGrid.truncated_impulse_response() naturally produces here -- see
that script's own comment), with a genuinely multi-tap Rx FFE (unlike
this project's real C2C config).
"""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np
import numpy.typing as npt

from serdeskit.common.types import Signal
from serdeskit.ctle import TwoStageCtle
from serdeskit.ffe import TapWeightFfe
from serdeskit.link import Link, SystemGrid
from serdeskit.rx_ffe import TapWeightRxFfe

DATA = Path(__file__).parent.parent.parent / "matlab_golden" / "data" / "apply_eq_with_rx_ffe.csv"

BAUD_RATE = 53.125e9
FREQ_STEP = 10e6
SAMPLES_PER_UI = 32
N = 3200  # pre-truncation length; grid.truncated_impulse_response() cuts this down to 1214
PEAK_IDX = 800  # 0-indexed


class _Identity:
    """A stage with H(f)=1 everywhere -- stands in for tx_filter/rx_afe
    so channel.transfer_function() alone determines Link's composed h.
    """

    def transfer_function(self, freqs: npt.NDArray[np.float64]) -> npt.NDArray[np.complex128]:
        return np.ones_like(freqs, dtype=np.complex128)


class _SyntheticChannel:
    """transfer_function() is fixed at construction -- chosen so that
    grid.truncated_impulse_response() reproduces a known, exact array
    (see module docstring). process() is unused by sbr_pulse_response().
    """

    def __init__(self, h: npt.NDArray[np.complex128]) -> None:
        self._h = h

    def transfer_function(self, freqs: npt.NDArray[np.float64]) -> npt.NDArray[np.complex128]:
        return self._h

    def process(self, sig: Signal) -> Signal:
        raise NotImplementedError


def test_matches_matlabs_real_eq_pulse_response() -> None:
    with open(DATA) as f:
        rows = list(csv.DictReader(f))
    expected = np.array([float(r["response"]) for r in rows])

    grid = SystemGrid.build(BAUD_RATE, FREQ_STEP, SAMPLES_PER_UI)
    k = np.arange(N)
    synthetic = np.exp(-np.abs(k - PEAK_IDX) / 60) * np.cos((k - PEAK_IDX) * 0.03)
    padded = np.zeros(len(grid.t))
    padded[:N] = synthetic
    h = np.fft.rfft(padded)
    channel = _SyntheticChannel(h)

    ctle = TwoStageCtle(
        zero_freq=21.25e9,
        pole1_freq=21.25e9,
        pole2_freq=53.125e9,
        shelf_freq=0.6640625e9,
        dc_gain_db=-3.0,
        shelf_gain_db=-2.0,
    )
    ffe = TapWeightFfe(tap_weights=np.array([0.1, -0.05]), n_post=1, tap_delay=1.0 / BAUD_RATE)
    rx_ffe = TapWeightRxFfe(tap_weights=np.array([0.05, 0.15, 1.0]), tap_delay=1.0 / BAUD_RATE, n_pre=2)

    link = Link(channel=channel, tx_filter=_Identity(), ctle=ctle, ffe=ffe, rx_afe=_Identity(), rx_ffe=rx_ffe)
    actual = link.sbr_pulse_response(grid).samples

    np.testing.assert_allclose(actual, expected, rtol=1e-9, atol=1e-9)
